const envRules = {
  ENV: {source: 'ENV'},
  TIMEZONE: {source: 'TIMEZONE', default: 'America/Chicago'},

  MONGO_MONGO_ROOT_URL: {source: 'DB.MONGO.MONGO_ROOT_URL'},

  AUTH_MONGO_URL: {source: 'DB.Authentication.MONGO_URL'},
  BILLING_MONGO_URL: {source: 'DB.Billing.MONGO_URL'},
  CONTENTPLAYER_MONGO_URL: {source: 'DB.ContentPlayer.MONGO_URL'},
  DATA_EXTRACT_MONGO_URL: {source: 'DB.DataExtract.MONGO_URL'},
  DVP_MONGO_URL: {source: 'DB.DVP.MONGO_URL'},
  ECOMMERCE_MONGO_URL: {source: 'DB.Ecommerce.MONGO_URL'},
  EXTERNAL_SCORING_MONGO_URL: {source: 'DB.ExternalScoring.MONGO_URL'},
  HIRING_MONGO_URL: {source: 'DB.Hiring.MONGO_URL'},
  WONSCORE_MONGO_URL: {source: 'DB.Wonscore.MONGO_URL'},
  HIRING_CONNECTOR_MONGO_URL: {source: 'DB.HiringConnector.MONGO_URL'},
  JOB_DIRECTORY_MONGO_URL: {source: 'DB.JobDirectory.MONGO_URL'},
  MAILER_MONGO_URL: {source: 'DB.Mailer.MONGO_URL'},
  NOTIFICATION_MONGO_URL: {source: 'DB.Notification.MONGO_URL'},
  WONLINK_MONGO_URL: {source: 'DB.WonLink.MONGO_URL'},
  WONDERLIC_ONLINE_CONNECTOR_MONGO_URL: {source: 'DB.WonderlicOnlineConnector.MONGO_URL'},
  WORKFLOW_ENGINE_MONGO_URL: {source: 'DB.WorkflowEngine.MONGO_URL'},
  INTEGRATION_ACQUIRETM_MONGO_URL: {source: 'DB.Integration.AcquireTM.MONGO_URL'},
  INTEGRATION_APPLICANTPRO_MONGO_URL: {source: 'DB.Integration.ApplicantPro.MONGO_URL'},
  INTEGRATION_BIZMERLIN_MONGO_URL: {source: 'DB.Integration.BizMerlin.MONGO_URL'},
  INTEGRATION_HIRINGTHING_MONGO_URL: {source: 'DB.Integration.HiringThing.MONGO_URL'},
  INTEGRATION_ICIMS_MONGO_URL: {source: 'DB.Integration.ICIMS.MONGO_URL'},
  INTEGRATION_ICIMS_V2_MONGO_URL: {source: 'DB.Integration.ICIMS_v2.MONGO_URL'},
  INTEGRATION_JOBMA_MONGO_URL: {source: 'DB.Integration.Jobma.MONGO_URL'},
  INTEGRATION_NEWTON_MONGO_URL: {source: 'DB.Integration.Newton.MONGO_URL'},
  INTEGRATION_GREENHOUSE_MONGO_URL: {source: 'DB.Integration.Greenhouse.MONGO_URL'},
  ITEM_BANK_MONGO_URL: {source: 'DB.ItemBank.MONGO_URL'},
  WONSCORE_INTEGRATION_MONGO_URL: {source: 'DB.WonscoreIntegration.MONGO_URL'},
  UNIFIED_ACCOUNT_MONGO_URL: {source: 'DB.UnifiedAccount.MONGO_URL'},

  AUTH_MONGO_RO_URL: {source: 'DB.Authentication.MONGO_RO_URL'},
  BILLING_MONGO_RO_URL: {source: 'DB.Billing.MONGO_RO_URL'},
  CONTENTPLAYER_MONGO_RO_URL: {source: 'DB.ContentPlayer.MONGO_RO_URL'},
  DATA_EXTRACT_MONGO_RO_URL: {source: 'DB.DataExtract.MONGO_RO_URL'},
  ECOMMERCE_MONGO_RO_URL: {source: 'DB.Ecommerce.MONGO_RO_URL'},
  EXTERNAL_SCORING_MONGO_RO_URL: {source: 'DB.ExternalScoring.MONGO_RO_URL'},
  HIRING_MONGO_RO_URL: {source: 'DB.Hiring.MONGO_RO_URL'},
  HIRING_CONNECTOR_MONGO_RO_URL: {source: 'DB.HiringConnector.MONGO_RO_URL'},
  JOB_DIRECTORY_MONGO_RO_URL: {source: 'DB.JobDirectory.MONGO_RO_URL'},
  MAILER_MONGO_RO_URL: {source: 'DB.Mailer.MONGO_RO_URL'},
  NOTIFICATION_MONGO_RO_URL: {source: 'DB.Notification.MONGO_RO_URL'},
  UNIFIED_ACCOUNT_MONGO_RO_URL: {source: 'DB.UnifiedAccount.MONGO_RO_URL'},
  WONLINK_MONGO_RO_URL: {source: 'DB.WonLink.MONGO_RO_URL'},
  WONSCORE_MONGO_RO_URL: {source: 'DB.Wonscore.MONGO_RO_URL'},
  WONDERLIC_ONLINE_CONNECTOR_MONGO_RO_URL: {source: 'DB.WonderlicOnlineConnector.MONGO_RO_URL'},
  WORKFLOW_ENGINE_MONGO_RO_URL: {source: 'DB.WorkflowEngine.MONGO_RO_URL'},
  INTEGRATION_ACQUIRETM_MONGO_RO_URL: {source: 'DB.Integration.AcquireTM.MONGO_RO_URL'},
  INTEGRATION_APPLICANTPRO_MONGO_RO_URL: {source: 'DB.Integration.ApplicantPro.MONGO_RO_URL'},
  INTEGRATION_BIZMERLIN_MONGO_RO_URL: {source: 'DB.Integration.BizMerlin.MONGO_RO_URL'},
  INTEGRATION_HIRINGTHING_MONGO_RO_URL: {source: 'DB.Integration.HiringThing.MONGO_RO_URL'},
  INTEGRATION_ICIMS_MONGO_RO_URL: {source: 'DB.Integration.ICIMS.MONGO_RO_URL'},
  INTEGRATION_ICIMS_V2_MONGO_RO_URL: {source: 'DB.Integration.ICIMS_v2.MONGO_RO_URL'},
  INTEGRATION_JOBMA_MONGO_RO_URL: {source: 'DB.Integration.Jobma.MONGO_RO_URL'},
  INTEGRATION_NEWTON_MONGO_RO_URL: {source: 'DB.Integration.Newton.MONGO_RO_URL'},
  INTEGRATION_GREENHOUSE_MONGO_RO_URL: {source: 'DB.Integration.Greenhouse.MONGO_RO_URL'},
  ITEM_BANK_MONGO_RO_URL: {source: 'DB.ItemBank.MONGO_RO_URL'},
  WONSCORE_INTEGRATION_MONGO_RO_URL: {source: 'DB.WonscoreIntegration.MONGO_RO_URL'},

  API_AUTH_URL: {source: 'API.Authentication.URL'},
  API_BILLING_URL: {source: 'API.Billing.URL'},
  API_DVP_URL: {source: 'API.DVP.URL'},
  API_ECOMMERCE_URL: {source: 'API.Ecommerce.URL'},
  API_HIRING_URL: {source: 'API.Hiring.URL'},
  API_NOTIFICATION_URL: {source: 'API.Notification.URL'},
  API_UNIFIED_ACCOUNT_URL: {source: 'API.UnifiedAccount.URL'},
  API_WONSCORE_URL: {source: 'API.Wonscore.URL'},

  AUTH_URL: {source: 'WebUI.Authentication.URL'},
  ECOMMERCE_WEBUI_URL: {source: 'WebUI.Ecommerce.URL'},
  BILLING_WEBUI_URL: {source: 'WebUI.Billing.URL'},
  WONSCORE_WEBUI_URL: {source: 'WebUI.Wonscore.URL'},
  WONSCORE_TOOLKIT_URL: {source: 'WebUI.Toolkit.Wonscore.URL'},

  API_ECOMMERCE_AUTH_ID: {source: 'API.Ecommerce.AUTH_ID'},
  API_ECOMMERCE_AUTH_SECRET: {source: 'API.Ecommerce.AUTH_SECRET'},
  API_WONSCORE_AUTH_ID: {source: 'API.Wonscore.AUTH_ID'},
  API_WONSCORE_AUTH_SECRET: {source: 'API.Wonscore.AUTH_SECRET'},
  API_WONDERLIC_QA_AUTH_ID: {source: 'External.WonderlicQA.AUTH_ID'},
  API_WONDERLIC_QA_AUTH_SECRET: {source: 'External.WonderlicQA.AUTH_SECRET'},

  NETSUITE_ACCOUNT_ID: {source: 'NETSUITE.ACCOUNT_ID'},
  NETSUITE_USERNAME: {source: 'NETSUITE.USERNAME'},
  NETSUITE_PASSWORD: {source: 'NETSUITE.PASSWORD'},
  NETSUITE_RESTLETS_BASE_URL: {source: 'NETSUITE.RESTLETS.BASE_URL'},
  NETSUITE_RESTLETS_URL_CACHE_DURATION: {source: 'NETSUITE.RESTLETS.URL_CACHE_DURATION'},
  NETSUITE_RESTLETS_RETRY_COUNT_MAX: {source: 'NETSUITE.RESTLETS.RETRY_COUNT_MAX'},
  NETSUITE_RESTLETS_RETRY_DURATION: {source: 'NETSUITE.RESTLETS.RETRY_DURATION'},
  NETSUITE_RESTLETS_SCRIPT_ID_WONSCORE: {source: 'NETSUITE.RESTLETS.SCRIPT_IDS.Wonscore'},
  NETSUITE_RESTLETS_SCRIPT_ID_CHANNEL: {source: 'NETSUITE.RESTLETS.SCRIPT_IDS.Channel'},
  NETSUITE_RESTLETS_SCRIPT_ID_ICIMS: {source: 'NETSUITE.RESTLETS.SCRIPT_IDS.ICIMS'},

  STRIPE_API_KEY: {source: 'STRIPE.API_KEY'},
  STRIPE_API_VERSION: {source: 'STRIPE.API_VERSION'},

  MAXMIND_ACCOUNT_ID: {source: 'MAXMIND.ACCOUNT_ID'},
  MAXMIND_LICENSE_KEY: {source: 'MAXMIND.LICENSE_KEY'},

  EXPERT_CONSULTING_SQL_HOST: {source: `DB.ExternalScoring.ExpertConsulting.SQL_HOST`},
  EXPERT_CONSULTING_SQL_PORT: {
    source: `DB.ExternalScoring.ExpertConsulting.SQL_PORT`,
    required: false,
  },
  EXPERT_CONSULTING_SQL_DB: {source: `DB.ExternalScoring.ExpertConsulting.SQL_DB`},
  EXPERT_CONSULTING_SQL_USERNAME: {source: `DB.ExternalScoring.ExpertConsulting.SQL_USERNAME`},
  EXPERT_CONSULTING_SQL_PASSWORD: {source: `DB.ExternalScoring.ExpertConsulting.SQL_PASSWORD`},

  PUSHER_APP_ID: {source: 'PUSHER.APP_ID'},
  PUSHER_KEY: {source: 'PUSHER.KEY'},
  PUSHER_SECRET: {source: 'PUSHER.SECRET'},

  DEFAULT_EMAIL_ADDRESS: {source: 'API.Authentication.EMAIL_FROM_ADDRESS'},
};

const SERVICES = [
  'Authentication',
  'Billing',
  'ContentPlayer',
  'DataExtract',
  'DVP',
  'Ecommerce',
  'ItemBank',
  'JobDirectory',
  'Mailer',
  'Notification',
  'PDFGeneration',
  'Toolkit',
  'UnifiedAccount',
  'WonderlicOnlineConnector',
  'WonLink',
  'Wonscore',
  'WonscoreIntegration',
  'WorkflowEngine',
  'Privacy',
  'ResponseCollector',
  'WonscoreCandidate',
  'WorkflowEngineReact',
  'WonscoreApply',
];

for (const service of SERVICES) {
  envRules[`API_${service.toUpperCase()}_PORT`] = {source: `API.${service}.PORT`, required: false};
  envRules[`WEBUI_${service.toUpperCase()}_PORT`] = {
    source: `WebUI.${service}.PORT`,
    required: false,
  };
}

module.exports = envRules;
